---
title: "Create A Solid Match With Crop View In FloorPlan"
subTitle: "T·∫°o m·ªôt m·∫∑t Solid kh·ªõp v·ªõi Crop View trong m·∫∑t b·∫±ng"
category: dynamo
cover: cover.png
---

Ch√†o m·ª´ng c√°c b√°c ƒë√£ gh√© thƒÉm blog c·ªßa m√¨nh.üòÑ

### M·ªû ƒë·∫ßu

Scripts d∆∞·ªõi ƒë√¢y s·∫Ω cho ph√©p c√°c b√°c t·∫°o ra m·ªôt Solid kh·ªõp v·ªõi v√πng Crop View m√† ta ƒë√£ ƒë·ªãnh s·∫µn trong View ƒë√£ ch·ªçn.B√†i to√°n n√†y l√† t·ª´ m·ªôt ng∆∞·ªùi trong group h·ªèi m√¨nh vi·ªác ƒë·∫∑t kh·ªëi n√†y kh√¥ng kh·ªõp v·ªõi v·ªã tr√≠ mong mu·ªën.

### Scripts
``` csharp
public static Autodesk.DesignScript.Geometry.Solid CreateCutPlaneSolid(global::Revit.Elements.Element planv)
        {

            View planView = planv.InternalElement as View;
            BoundingBoxXYZ bbActiview = planView.get_BoundingBox(null);
            Plane planePlanView = planView.SketchPlane.GetPlane();
            PlanViewRange viewRange = (planView as ViewPlan).GetViewRange();
            double cutPlaneHeight = viewRange.GetOffset(PlanViewPlane.CutPlane);

            XYZ pt0 = new XYZ(bbActiview.Min.X, bbActiview.Min.Y, bbActiview.Min.Z);
            XYZ pt1 = new XYZ(bbActiview.Max.X, bbActiview.Min.Y, bbActiview.Min.Z);
            XYZ pt2 = new XYZ(bbActiview.Max.X, bbActiview.Max.Y, bbActiview.Min.Z);
            XYZ pt3 = new XYZ(bbActiview.Min.X, bbActiview.Max.Y, bbActiview.Min.Z);

            XYZ pt00 = ProjectOnto(planePlanView, pt0);
            XYZ pt11 = ProjectOnto(planePlanView, pt1);
            XYZ pt22 = ProjectOnto(planePlanView, pt2);
            XYZ pt33 = ProjectOnto(planePlanView, pt3);

            Line edge00 = Line.CreateBound(pt00, pt11);
            Line edge11 = Line.CreateBound(pt11, pt22);
            Line edge22 = Line.CreateBound(pt22, pt33);
            Line edge33 = Line.CreateBound(pt33, pt00);

            List<Curve> edges0 = new List<Curve>();
            edges0.Add(edge00);
            edges0.Add(edge11);
            edges0.Add(edge22);
            edges0.Add(edge33);

            CurveLoop baseLoop0 = CurveLoop.Create(edges0);
            List<CurveLoop> loopList0 = new List<CurveLoop>();
            loopList0.Add(baseLoop0);
            Solid preTransformSolid =
                GeometryCreationUtilities.CreateExtrusionGeometry(loopList0,
                    XYZ.BasisZ, cutPlaneHeight);
                    //transform
            Solid transformSolid = SolidUtils.CreateTransformed(preTransformSolid,
                bbActiview.Transform);

            return transformSolid.ToProtoType();
        }
        [IsVisibleInDynamoLibrary(false)]
        public static XYZ ProjectOnto(this Plane plane, XYZ p)
        {
            double d = plane.SignedDistanceTo(p);
            XYZ q = p - d * plane.Normal;

            return q;
        }
```

### ƒê∆∞a v√†o m√¥i tr∆∞·ªùng trong Dynamo ki·ªÉm tra 

![](pic/photo_2020-03-27_22-05-51.jpg)

### K·∫øt qu·∫£

![](pic/CropView.6589856986.gif)

### T·ªïng k·∫øt

B√†i to√°n n√†y g·ª£i m·ªü cho c√°c b√°c t·∫°o m·ªôt kh·ªëi Solid v√† ƒë∆∞a kh·ªëi Solid v·ªÅ v·ªã tr√≠ mong mu·ªën, bi·∫øt ƒë√¢u sau khi ƒë·ªçc xong b√†i n√†y c√°c b√°c l·∫°i c√≥ √Ω t∆∞·ªüng g√¨ ƒë√≥ cho c√¥ng vi·ªác g√¨ th√¨ sao.Cu·ªëi c√πng ch√∫c c√°c b√°c th·ª±c hi·ªán th√†nh c√¥ng.N·∫øu c√≥ √Ω t∆∞·ªüng g√¨ h√†y h√£y b√¨nh lu·∫≠n b√™n d∆∞·ªõi ƒë√≥ng g√≥p m√¨nh s·∫Ω b·ªï sung.Xin C·∫£m ∆°n c√°c b√°c ƒë√£ gh√©p thƒÉm blog cu·∫© m√¨nh.

### Tham kh·∫£o :
<a href="https://t.me/DynamoAPI" target="_blank">DynamoChat</a> 